### ISSUE TITLE
M_PI is deprecated

### ISSUE THREAD

**Issue by scottpchow23** [MakeSchool-Tutorials/Intro-Functions-Swift-Playground#17]
Depending on what type of pi you want, you now need to call it like so:
`let doublePi : Double = Double.pi`

**Comment by dionlarson** [comment]
Fixed in https://github.com/MakeSchool-Tutorials/Intro-Functions-Swift-Playground/commit/a7c5e5fbcecd84be835f95041f790a8093a7b6c7
