### ISSUE TITLE
P4 reference to curly braces is confusing

### ISSUE THREAD

**Issue by danstepanov** [MakeSchool-Tutorials/Intro-Functions-Swift-Playground#5]
`This is then followed by curly braces ({ and })`

**Comment by dionlarson** [comment]
Any thoughts on making it less confusing?

**Comment by danstepanov** [comment]
have you considered replacing it with "This is then followed by curly braces `{` and `}`" or perhaps "This is then followed by curly braces `{}`"

**Comment by dionlarson** [comment]
Ah, I see what you mean now. The parentheses makes it confusing... Thank you for pointing that out.
