### ISSUE TITLE
P10 Confusing phrasing

### ISSUE THREAD

**Issue by danstepanov** [MakeSchool-Tutorials/Intro-Functions-Swift-Playground#9]
<img width="488" alt="screen shot 2016-06-13 at 2 25 24 pm" src="https://cloud.githubusercontent.com/assets/5482800/16023708/e61e8ed6-3172-11e6-84d2-bf9b5ee99819.png">

The above image seems like a perfectly acceptable solution based on the instructions. I could see this being a potential source of confusion. Perhaps a hint could be provided to clarify how to ensure that the `return` type of `calculateRotationForPolygon()` is `Double`?

**Comment by dionlarson** [comment]
I meant for `rotate` to be able to take a `Double` or `Int`. Added that to the drawing functions and hint to the challenge.
